on: [push, pull_request]
name: main
jobs:
  ojs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #application: ['ojs']
        database: ['mysql']
        php-version: [ '8.1']
        #application: ['omp','ojs','ops']
        #database: ['pgsql','mysql']
        #php-version: [ '8.1' ,'8.2']

    name: ojs
    steps:
      - uses: xmlFlow/pkp-github-actions@v1
        with:
          test: true
          #upgrade: true
          application: 'ojs'
          repository: 'pkp'
          branch: 'main'

