on: [push, pull_request]
name: ojs
jobs:
  ojs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.1
            validate: true
          - php-version: 8.1
            database: pgsql
            test: true
            SAVE_BUILD: 1
          - php-version: 8.1
            database: mariadb
            test: true
            SAVE_BUILD: 1
          - php-version: 8.1
            database: mysql
            test: true
            SAVE_BUILD: 1
            upgrade: true
            upgrade_test: 'stable-3_3_0,stable-3_4_0'
          - php-version: 8.2
            database: mysql
            test: true
          - php-version: 8.2
            database: pgsql
            test: true



    name: ojs
    steps:
      - uses: xmlFlow/pkp-github-actions@v1
        with:
          node_version: 20
          dataset_branch: 'main'
          DATASETS_ACCESS_KEY:  ${{secrets.DATASETS_ACCESS_KEY}}
          DEBUG_IN_TMATE: true

