on: [push, pull_request]
name: main
jobs:
  ojs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database: ['mysql']
        #database: ['pgsql','mysql']
        php-version: [ '8.1' ]
        #php-version: [ '8.1' ,'8.2']

    name: ojs
    steps:
      - uses: xmlFlow/pkp-github-actions@v1
        with:
          #validate: true
          test: true
          upgrade: true


