name: PHPStan Analysis

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath, bz2, curl, gd, intl, mbstring, mysql,mysqlnd, mysqli, opcache, pdo_mysql, pgsql, json,soap, xml, zip

      - name: Install Composer dependencies
        run: |
          find . -maxdepth 4 -name composer.json -exec bash -c 'composer --no-ansi --working-dir="`dirname {}`" install --optimize-autoloader' ";"

      - name: Install PHPStan
        run: |
          composer require --dev phpstan/phpstan

      - name: Run PHPStan on lib/pkp/classes
        run: |
          echo "Running PHPStan on lib/pkp/classes..."
          vendor/bin/phpstan analyse /home/runner/work/ojs/ojs/lib/pkp/classes --memory-limit=2024M --level=max
          echo "Running PHPStan on lib/pkp/controllers..."
          echo "Running PHPStan on lib/pkp/pages..."
          vendor/bin/phpstan analyse /home/runner/work/ojs/ojs/lib/pkp/pages --memory-limit=2024M --level=max
          echo "Running PHPStan on lib/pkp/lib..."
          vendor/bin/phpstan analyse /home/runner/work/ojs/ojs/lib/pkp/lib --memory-limit=2024M --level=max
          echo "Running PHPStan on lib/pkp/tests..."
          vendor/bin/phpstan analyse /home/runner/work/ojs/ojs/lib/pkp/tests --memory-limit=2024M --level=max

      - name: Run PHPStan on remaining lib/pkp directories
        run: |
          echo "Running PHPStan on remaining lib/pkp directories..."
          vendor/bin/phpstan analyse /home/runner/work/ojs/ojs/lib/pkp --memory-limit=2024M --level=max --exclude-path="vendor/*,/home/runner/work/ojs/ojs/lib/pkp/{classes,controllers,pages,lib,tests}"

